version: 2

models:
  - name: stg_decidim_organizations
    description: "A staging model for Decidim organizations"
    columns:
      - name: id
        description: "Unique identifier for the organization"
      - name: name
        description: "Name of the organization"
      - name: host
        description: "Host URL for the organization"
      - name: default_locale
        description: "Default locale for the organization"
      - name: available_locales
        description: "List of available locales for the organization"
      - name: created_at
        description: "Timestamp when the organization was created"
      - name: description
        description: "Description of the organization"
      - name: secondary_hosts
        description: "Secondary hosts for the organization"
      - name: available_authorizations
        description: "List of available authorizations for the organization"
      - name: header_snippets
        description: "Header snippets for the organization"
      - name: tos_version
        description: "Version of the terms of service"
      - name: badges_enabled
        description: "Indicates if badges are enabled. Badges in Decidim recognize participant actions and progress, enhancing engagement through gamification."
      - name: send_welcome_notification
        description: "Flag indicating if welcome notifications are sent"
      - name: users_registration_mode
        description: "Mode of user registration"
      - name: time_zone
        description: "Time zone of the organization"

sources:
  - name: decidim
    database: "{{ env_var('DBNAME') }}"
    schema: public
    tables:
      - name: decidim_organizations
        description: "Table containing organization informations"