
version: 2

sources:
  - name: decidim
    database: "{{ env_var('DBNAME') }}"
    schema: public
    tables:
      - name: decidim_initiatives
        columns:
          - name: state
            data_tests:
              - not_null
              - accepted_values: { values: [ 0, 1, 2, 3, 4, 5, 6 ] }
      - name: decidim_initiatives_votes
      - name: decidim_initiatives_type_scopes
      


      






