cour_des_comptes:
  target: preprod
  outputs:
    dev:
      dbname: "{{ env_var('DBNAME') }}"
      host: "{{ env_var('HOST') }}"
      pass: "{{ env_var('PASSWORD') }}"
      port: "{{ env_var('PORT') | as_number }}"
      schema: "{{ env_var('TARGET_SCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('USER') }}"
    preprod:
      dbname: "{{ env_var('DBNAME') }}"
      host: "{{ env_var('HOST_PREPROD') }}"
      pass: "{{ env_var('PASSWORD_PREPROD') }}"
      port: "{{ env_var('PORT_PREPROD') | as_number }}"
      schema: "{{ env_var('TARGET_SCHEMA_PREPROD') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('USER_PREPROD') }}"
    prod:
      dbname: "{{ env_var('DBNAME') }}"
      host: "{{ env_var('HOST') }}"
      pass: "{{ env_var('PASSWORD') }}"
      port: "{{ env_var('PORT') | as_number }}"
      schema: "{{ env_var('TARGET_SCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('USER') }}"