unit_tests:
  - name: resource_type_definition
    description: "Checks that the resource type is properly defined"
    model: stg_decidim_proposals
    given:
      - input: source('decidim', 'decidim_proposals_proposals')
        format: dict
        rows:
          - {id: 1}
    expect:
      format: dict
      rows:
          - {resource_type: 'Decidim::Proposals::Proposal'}