
version: 2

models:
  - name: project_votes
    schema: "{{ env_var('TARGET_SCHEMA') }}"
    description: "Splits budgets orders (i.e. votes) on a per-project basis"
    columns:
      - name: order_id
        description: "ID of the budget order through which the vote has been issued"    