
version: 2

models:
  - name: projects_votes
    description: "Splits budgets orders (i.e. votes) on a per-project basis"
    columns:
      - name: order_id
        description: "ID of the budget order through which the vote has been issued"    

unit_tests:
  - name: test_translate_category
    description: "Check that the category is translated correctly to French"
    model: budgets_projects
    overrides:
      env_vars:
        LANG: 'fr'  
    given:
      - input: ref('stg_decidim_budgets')
        format: dict
        rows:
          - {id: 1}
          - {id: 2}
      - input: ref('int_budgets_projects')
        format: dict
        rows:
          - {id: 1, project_amount: 1000, selected_at: '2022-01-01', is_selected: true}
          - {id: 2, project_amount: 2000, selected_at: '2022-02-01', is_selected: false}
      - input: ref('components')
        format: dict
        rows:
          - {id: 1, component_url: 'http://example.com', manifest_name: 'manifest1'}
          - {id: 2, component_url: 'http://example2.com', manifest_name: 'manifest2'}
      - input: ref('categorizations')
        format: dict
        rows:
          - {categorizable_id: 1, category_name: 'Environnement', child_name: 'Energie'}
          - {categorizable_id: 2, category_name: '', child_name: ''}
    expect:
      format: dict
      rows:
        - {first_category: 'Environnement', first_sub_category: 'Energie'} 
        - {first_category: 'Sans catégorie', first_sub_category: 'Sans sous-catégorie'} 
  - name: test_translate_category_multilingual
    description: "Check that the category is translated correctly to Dutch"
    model: budgets_projects
    overrides:
      env_vars:
        LANG: 'nl'  
    given:
      - input: ref('stg_decidim_budgets')
        format: dict
        rows:
          - {id: 1}
          - {id: 2}
      - input: ref('int_budgets_projects')
        format: dict
        rows:
          - {id: 1, project_amount: 1000, selected_at: '2022-01-01', is_selected: true}
          - {id: 2, project_amount: 2000, selected_at: '2022-02-01', is_selected: false}
      - input: ref('components')
        format: dict
        rows:
          - {id: 1, component_url: 'http://example.com', manifest_name: 'manifest1'}
          - {id: 2, component_url: 'http://example2.com', manifest_name: 'manifest2'}
      - input: ref('categorizations')
        format: dict
        rows:
          - {categorizable_id: 1, category_name: 'Gezondheid', child_name: 'Zorg'}
          - {categorizable_id: 2, category_name: '', child_name: ''}
    expect:
      format: dict
      rows:
        - {category: 'Gezondheid'}  
        - {category: 'Geen categorie'}  


  