version: 2

models:
  - name: projects_votes
    description: "Splits budgets orders (i.e. votes) on a per-project basis"
    config:
      contract: {enforced: true}
    columns:
      - name: order_id
        data_type: BIGINT
        description: "ID of the budget order through which the vote has been issued"    
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('int_budget_orders')
            to_columns: id
      - name: decidim_user_id
        data_type: BIGINT
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('users')
            to_columns: id
      - name: project_id
        data_type: BIGINT
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('budgets_projects')
            to_columns: id
      - name: project_title
        data_type: STRING
      - name: decidim_component_id
        data_type: BIGINT
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('components')
            to_columns: id
      - name: created_at
        data_type: TIMESTAMP
      - name: checked_out_at
        data_type: TIMESTAMP
      - name: project_url
        data_type: STRING
      - name: vote_finished
        data_type: BOOL
      - name: decidim_budgets_budget_id
        data_type: BIGINT
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('budgets')
            to_columns: id
unit_tests:
  - name: test_translate_category
    description: "Check that the category is translated correctly to French"
    model: budgets_projects
    overrides:
      vars:
        DBT_LANG: 'fr'
    given:
      - input: ref('stg_decidim_budgets')
        format: dict
        rows:
          - {id: 42, decidim_component_id: 1}
          - {id: 43, decidim_component_id: 2}
      - input: ref('int_budgets_projects')
        format: dict
        rows:
          - {id: 1, decidim_budgets_budget_id: 42, project_amount: 1000, selected_at: '2022-01-01', is_selected: true}
          - {id: 2, decidim_budgets_budget_id: 43, project_amount: 2000, selected_at: '2022-02-01', is_selected: false}
      - input: ref('components')
        format: dict
        rows:
          - {id: 1, component_url: 'http://example.com', manifest_name: 'manifest1'}
          - {id: 2, component_url: 'http://example2.com', manifest_name: 'manifest2'}
      - input: ref('categorizations')
        format: dict
        rows:
          - {categorizable_id: 1, categorizable_type: 'Decidim::Budgets::Project', category_name: 'Environnement', child_name: 'Energie'}
          - {categorizable_id: 2, categorizable_type: 'Decidim::Budgets::Project', category_name: '', child_name: ''}
    expect:
      format: dict
      rows:
        - {first_category: 'Environnement', first_sub_category: 'Energie'}
        - {first_category: 'Sans catégorie', first_sub_category: 'Sans sous-catégorie'}

  - name: test_translate_category_multilingual
    description: "Check that the category is translated correctly to Dutch"
    model: budgets_projects
    overrides:
      vars:
        DBT_LANG: 'nl'
    given:
      - input: ref('stg_decidim_budgets')
        format: dict
        rows:
          - {id: 42, decidim_component_id: 1}
          - {id: 43, decidim_component_id: 2}
      - input: ref('int_budgets_projects')
        format: dict
        rows:
          - {id: 1, decidim_budgets_budget_id: 42, project_amount: 1000, selected_at: '2022-01-01', is_selected: true}
          - {id: 2, decidim_budgets_budget_id: 43, project_amount: 2000, selected_at: '2022-02-01', is_selected: false}
      - input: ref('components')
        format: dict
        rows:
          - {id: 1, component_url: 'http://example.com', manifest_name: 'manifest1'}
          - {id: 2, component_url: 'http://example2.com', manifest_name: 'manifest2'}
      - input: ref('categorizations')
        format: dict
        rows:
          - {categorizable_id: 1, categorizable_type: 'Decidim::Budgets::Project', category_name: 'Gezondheid', child_name: 'Zorg'}
          - {categorizable_id: 2, categorizable_type: 'Decidim::Budgets::Project', category_name: '', child_name: ''}
    expect:
      format: dict
      rows:
        - {first_category: 'Gezondheid', first_sub_category: 'Zorg'}
        - {first_category: 'Geen categorie', first_sub_category: 'Geen subcategorie'}
