version: 2

models:
  - name: int_matomo_referrers
    schema: "{{ env_var('TARGET_SCHEMA') }}"
    description: Info about visits linked to a referrer (a referrer describes a channel acquisition your visitors used to get to your website. Referrers are sorted by type, such as search engines, social networks, direct entries...)
    columns:
      - name: renamed_label
        description: Undefined keyword is due to Matomo being unable to fetch keyword typed in most search engines, and is not acceptable in user-facing dashboards
  - name: int_matomo_visits
    schema: "{{ env_var('TARGET_SCHEMA') }}"
    description: If a visitor comes for the first time or if they visit a page more than 30 minutes after their last page view, this will be recorded as a new visit
    columns:
      - name: bounce_rate_as_number
        description: Recalculted bounce rate in order to be handled as a number
      - name: daily_average_visit_length
        description: Calculated length of visit per day

unit_tests:
  - name: renamed_label_check
    description: "Check that the label is properly renamed"
    model: int_matomo_referrers
    overrides:
      vars:
        DBT_LANG: 'fr'
    given:
      - input: ref('stg_matomo_referrers')
        format: dict
        rows:
          - {label: 'Mot clef indéfini'}
    expect:
      format: dict
      rows:
          - {renamed_label: 'Moteur de recherche'}
  - name: test_translate_renamed_label_nl
    description: "Check that the renamed_label is correctly translated to Dutch"
    model: int_matomo_referrers
    overrides:
      vars:
        DBT_LANG: 'nl'  
    given:
      - input: ref('stg_matomo_referrers')
        format: dict
        rows:
          - {label: 'Mot clef indéfini'}
          - {label: 'Search engine'}
          - {label: 'Other label'}
    expect:
      format: dict
      rows:
        - {renamed_label: 'Zoekmachine'}   
        - {renamed_label: 'Search engine'} 
        - {renamed_label: 'Other label'}  

  - name: test_translate_sub_type_en
    description: "Check that the sub_type is correctly translated to English"
    model: int_matomo_referrers
    overrides:
      vars:
        DBT_LANG: 'en'
    given:
      - input: ref('stg_matomo_referrers')
        format: dict
        rows:
          - {sub_type: 'Campagnes'}
          - {sub_type: 'Sites web'}
          - {sub_type: 'Moteurs de recherche'}
          - {sub_type: 'Réseaux sociaux'}
    expect:
      format: dict
      rows:
        - {sub_type: 'Campaigns'}
        - {sub_type: 'Websites'}
        - {sub_type: 'Search engines'}
        - {sub_type: 'Social networks'}

  - name: test_translate_sub_type_de
    description: "Check that the sub_type is correctly translated to German"
    model: int_matomo_referrers
    overrides:
      vars:
        DBT_LANG: 'de'
    given:
      - input: ref('stg_matomo_referrers')
        format: dict
        rows:
          - {sub_type: 'Campagnes'}
          - {sub_type: 'Sites web'}
          - {sub_type: 'Moteurs de recherche'}
          - {sub_type: 'Réseaux sociaux'}
    expect:
      format: dict
      rows:
        - {sub_type: 'Kampagnen'}
        - {sub_type: 'Websites'}
        - {sub_type: 'Suchmaschinen'}
        - {sub_type: 'Soziale Netzwerke'}

  - name: test_translate_sub_type_unknown
    description: "Check that unknown sub_type values return 'Unknown'"
    model: int_matomo_referrers
    overrides:
      vars:
        DBT_LANG: 'fr'
    given:
      - input: ref('stg_matomo_referrers')
        format: dict
        rows:
          - {sub_type: 'Autre valeur'}
          - {sub_type: NULL}
    expect:
      format: dict
      rows:
        - {sub_type: 'Inconnu'}
        - {sub_type: 'Unknown'}
