version: 2

sources:
  - name: decidim
    database: "{{ env_var('DBNAME') }}"
    schema: public  
    tables:
      - name: decidim_proposals_proposals
      - name: decidim_proposals_proposal_states
