models:
  - name: debates
    config:
      contract: {enforced: true}
    columns:
      - name: id
        data_type: bigint
        constraints:
          - type: unique
          - type: not_null
          - type: primary_key
      - name: title
        data_type: text
      - name: description
        data_type: text
      - name: start_time
        data_type: timestamp
      - name: end_time
        data_type: timestamp
      - name: decidim_component_id
        data_type: bigint
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('components')
            to_columns: [id]
      - name: decidim_author_id
        data_type: bigint
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('users')
            to_columns: [id]
      - name: created_at
        data_type: timestamp
      - name: closed_at
        data_type: timestamp
      - name: ps_slug
        data_type: text
      - name: debate_url
        data_type: text
      - name: resource_type
        data_type: text
      - name: categories
        data_type: text #array
      - name: first_category
        data_type: text
      - name: sub_categories
        data_type: text #array
      - name: first_sub_category
        data_type: text