version: 2

models:
  - name: int_decidim_awesome_private_proposal_fields
    description: "Model for parsing the information in the private proposals fields and unnest the XML data into readable questions and answers columns."
    columns:
      - name: id
        description: "Primary key."
      - name: proposal_id
        description: "Id of the proposal the private field is linked to."
      - name: private_field_description
        description: "Description of the private field to be answered."
      - name: private_field_content
        description: "The content filled by the user for a specific private field. There can be multiple content for the same private field description."


unit_tests:

   - name: testing_that_the_correct_xml_information_are_parsed
     description: "Checks that age matching fetches the correct infos "
     model: int_decidim_awesome_private_proposal_fields
     given:
      - input: ref('stg_decidim_awesome_private_proposal_fields')
        format: dict
        rows:
          - {id: 1, proposal_id: 101, private_body: '<xml><dl class="decidim_awesome-custom_fields" data-generator="decidim_awesome" data-version="0.9.2"><dt name="radio-group-1724336804706-0">Vous êtes :</dt><dd id="radio-group-1724336804706-0" name="radio-group"><div alt="sans_emploi">Sans emploi</div></dd><dt name="number-1724336900935-0">Code postal</dt><dd id="number-1724336900935-0" name="number"><div>75003</div></dd><dt name="checkbox-group-1724336967989-0">Comment avez-vous eu connaissance de la plateforme ?</dt><dd id="checkbox-group-1724336967989-0" name="checkbox-group"><div alt="option2">Par la Cour des comptes et les CRTC (site web, réseaux sociaux…)</div><div alt="option5">Par mon entourage personnel ou professionnel</div></dd></dl></xml>'}
     expect:
      format: dict
      rows:
        - {id: 1, proposal_id: 101, private_field_description: "Vous êtes :", private_field_content: "Sans emploi"}
        - {id: 1, proposal_id: 101, private_field_description: "Code postal", private_field_content: "75003"}
        - {id: 1, proposal_id: 101, private_field_description: "Comment avez-vous eu connaissance de la plateforme ?", private_field_content: "Par la Cour des comptes et les CRTC (site web, réseaux sociaux…)"}
        - {id: 1, proposal_id: 101, private_field_description: "Comment avez-vous eu connaissance de la plateforme ?", private_field_content: "Par mon entourage personnel ou professionnel"}