unit_tests:
  - name: int_forms_answers_author_status_check
    description: "Check that the author status is correctly detected"
    model: int_forms_answers
    overrides:
      vars:
        DBT_LANG: 'fr'  
    given:
      - input: ref('stg_decidim_forms_answers')
        format: dict
        rows:
          - {decidim_user_id: 1}
          - {decidim_user_id: NULL}
    expect:
      format: dict
      rows:
        - {author_status: "Inscrit et connecté"}
        - {author_status: "Non connecté"}
  - name: int_forms_answers_author_status_check_multilingual
    description: "Check that the author status is correctly detected in Dutch"
    model: int_forms_answers
    overrides:
      vars:
        DBT_LANG: 'nl'  
    given:
      - input: ref('stg_decidim_forms_answers')
        format: dict
        rows:
          - {decidim_user_id: 1}
          - {decidim_user_id: NULL}
    expect:
      format: dict  
      rows:
        - {author_status: "Geregistreerd en ingelogd"}  
        - {author_status: "Uitgelogd"}  
  - name: answers_short_and_long_answer_check
    description: "Check if option and sorting answers are correctly processed in the answers_short_and_long_answer CTE"
    model: answers_short_and_long_answer
    overrides:
      vars:
        DBT_LANG: 'fr' 
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 1, decidim_question_id: 41, body: 'Answer 1'}
          - {id: 2, decidim_question_id: 42, body: NULL}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
          - {id: 41, decidim_questionnaire_id: 101, body: '{"fr": "Question 1"}', position: 1, question_type: 'short_answer'}
          - {id: 42, decidim_questionnaire_id: 101, body: '{"fr": "Question 2"}', position: 2, question_type: 'long_answer'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 1}
          - {decidim_answer_id: 2}
      - input: ref('forms')
        format: dict
        rows:
          - {id: 101}
    expect:
      format: dict
      rows:
        - {answer: 'Answer 1', sub_matrix_question: '', custom_body: '', sorting_position: -1, decidim_questionnaire_id: 101, position: 1}
        - {answer: 'Pas de réponse', sub_matrix_question: '', custom_body: '', sorting_position: -1, decidim_questionnaire_id: 101, position: 2}
  - name: answers_short_and_long_answer_check_multilingual
    description: "Check if option and sorting answers are correctly processed in German"
    model: answers_short_and_long_answer
    overrides:
      vars:
        DBT_LANG: 'de'
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 1, decidim_question_id: 41, body: 'Answer 1'}
          - {id: 2, decidim_question_id: 42, body: NULL}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
          - {id: 41, decidim_questionnaire_id: 101, body: '{"de": "Frage 1"}', position: 1, question_type: 'short_answer'}
          - {id: 42, decidim_questionnaire_id: 101, body: '{"de": "Frage 2"}', position: 2, question_type: 'long_answer'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 1}
          - {decidim_answer_id: 2}
      - input: ref('forms')
        format: dict
        rows:
          - {id: 101}
    expect:
      format: dict
      rows:
        - {answer: 'Answer 1', sub_matrix_question: '', custom_body: '', sorting_position: -1, decidim_questionnaire_id: 101, position: 1}
        - {answer: 'Keine Antwort', sub_matrix_question: '', custom_body: '', sorting_position: -1, decidim_questionnaire_id: 101, position: 2}
  - name: answers_matrix_check
    description: "Check if matrix answers are correctly processed"
    model: all_answers_matrix
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 901, decidim_question_id: 41}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
          - {id: 41, decidim_questionnaire_id: 101, body: "How often do you go there ?", question_type: 'matrix_single'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 901, body: 'Rarely', decidim_question_matrix_row_id: 1, decidim_answer_option_id: 1001}
          - {decidim_answer_id: 901, body: 'Never', decidim_question_matrix_row_id: 2, decidim_answer_option_id: 1002}
          - {decidim_answer_id: 901, body: 'Often', decidim_question_matrix_row_id: 3, decidim_answer_option_id: 1003}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 1001}
          - {id: 1002}
          - {id: 1003}
      - input: ref('stg_decidim_forms_question_matrix_rows')
        format: dict
        rows:
          - {id: 1, body: 'Place 1'}
          - {id: 2, body: 'Place 2'}
          - {id: 3, body: 'Place 3'}
    expect:
      format: dict
      rows:
        - {body: "How often do you go there ?", answer: "Rarely", sub_matrix_question: "Place 1", sorting_position: -1, decidim_questionnaire_id: 101, custom_body: '', question_type: 'matrix_single'}
        - {body: "How often do you go there ?", answer: "Never", sub_matrix_question: "Place 2", sorting_position: -1, decidim_questionnaire_id: 101, custom_body: '', question_type: 'matrix_single'}
        - {body: "How often do you go there ?", answer: "Often", sub_matrix_question: "Place 3", sorting_position: -1, decidim_questionnaire_id: 101, custom_body: '', question_type: 'matrix_single'}

  - name: answers_option_and_sorting_check_on_question_type
    description: "Check that question_type is correctly taken into account"
    model: all_answers_option_and_sorting
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 901, decidim_question_id: 41}
          - {id: 902, decidim_question_id: 42}
          - {id: 903, decidim_question_id: 43}
          - {id: 904, decidim_question_id: 44}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
          - {id: 41, question_type: 'single_option'}
          - {id: 42, question_type: 'multiple_option'}
          - {id: 43, question_type: 'sorting'}
          - {id: 44, question_type: 'matrix_single'}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 1}
          - {id: 2}
          - {id: 3}
          - {id: 4}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 901, decidim_answer_option_id: 1}
          - {decidim_answer_id: 902, decidim_answer_option_id: 2}
          - {decidim_answer_id: 903, decidim_answer_option_id: 3}
          - {decidim_answer_id: 904, decidim_answer_option_id: 4}
    expect:
      format: dict
      rows:
          - {question_type: 'single_option'}
          - {question_type: 'multiple_option'}
          - {question_type: 'sorting'}

  - name: short_and_long_answer_check_on_question_type
    description: "Check that question_type is correctly taken into account"
    model: answers_short_and_long_answer
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 901, decidim_question_id: 41, body: "Nord"}
          - {id: 902, decidim_question_id: 42, body: "Rouge"}
          - {id: 903, decidim_question_id: 43, body: "Hiver"}
          - {id: 904, decidim_question_id: 44, body: "réponse matrix"}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
          - {id: 41, question_type: 'short_answer'}
          - {id: 42, question_type: 'long_answer'}
          - {id: 43, question_type: 'sorting'}
          - {id: 44, question_type: 'matrix_single'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 901}
          - {decidim_answer_id: 902}
          - {decidim_answer_id: 903}
          - {decidim_answer_id: 904}

    expect:
      format: dict
      rows:
          - {question_type: 'short_answer'}
          - {question_type: 'long_answer'}

  - name: answers_matrix_check_on_question_type
    description: "Check that question_type is correctly taken into account"
    model: all_answers_matrix
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 901, decidim_question_id: 41}
          - {id: 902, decidim_question_id: 42}
          - {id: 903, decidim_question_id: 43}
          - {id: 904, decidim_question_id: 44}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
          - {id: 41, question_type: 'short_answer'}
          - {id: 42, question_type: 'long_answer'}
          - {id: 43, question_type: 'matrix_multiple'}
          - {id: 44, question_type: 'matrix_single'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 903, decidim_question_matrix_row_id: 1, decidim_answer_option_id: 1001}
          - {decidim_answer_id: 904, decidim_question_matrix_row_id: 2, decidim_answer_option_id: 1002}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 1001}
          - {id: 1002}
      - input: ref('stg_decidim_forms_question_matrix_rows')
        format: dict
        rows:
          - {id: 1}
          - {id: 2}
          - {id: 3}
    expect:
      format: dict
      rows:
          - {question_type: 'matrix_multiple'}
          - {question_type: 'matrix_single'}

  - name: answers_matrix_custom_body_check
    description: "Check if custom bodies are correctly retrieved from matrix answers"
    model: all_answers_matrix
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 901, session_token: 555555, decidim_question_id: 41}
          - {id: 902, session_token: 666666, decidim_question_id: 41}
          - {id: 903, session_token: 555555, decidim_question_id: 42}
          - {id: 904, session_token: 666666, decidim_question_id: 42}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
          - {id: 41, question_type: 'matrix_single', body: "Qu'en avez-vous pensé ?"}
          - {id: 42, question_type: 'matrix_multiple', body: "Quel rôle avez-vous joué ?"}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 901, decidim_question_matrix_row_id: 1, body: "Rien (précisez pourquoi)", custom_body: "Pas joué", decidim_answer_option_id: 1001}
          - {decidim_answer_id: 902, decidim_question_matrix_row_id: 1, body: "Bon match", custom_body: NULL, decidim_answer_option_id: 1002}
          - {decidim_answer_id: 903, decidim_question_matrix_row_id: 8, body: "Autre (précisez lequel)", custom_body: "Arbitre", decidim_answer_option_id: 1003}
          - {decidim_answer_id: 904, decidim_question_matrix_row_id: 8, body: "Attaquant", custom_body: NULL, decidim_answer_option_id: 1004}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 1001}
          - {id: 1002}
          - {id: 1003}
          - {id: 1004}
      - input: ref('stg_decidim_forms_question_matrix_rows')
        format: dict
        rows:
          - {id: 1}
          - {id: 8}
    expect:
      format: dict
      rows:
        - {session_token: 555555, body: "Qu'en avez-vous pensé ?", answer: "Rien (précisez pourquoi)", custom_body: "Pas joué"}
        - {session_token: 666666, body: "Qu'en avez-vous pensé ?", answer: "Bon match", custom_body: ''}
        - {session_token: 555555, body: "Quel rôle avez-vous joué ?", answer: "Autre (précisez lequel)", custom_body: "Arbitre"}
        - {session_token: 666666, body: "Quel rôle avez-vous joué ?", answer: "Attaquant", custom_body: ''}

  - name: answers_single_option_content_check
    description: "Check that single option answers match pre-written options"
    model: all_answers_option_and_sorting
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 901, decidim_question_id: 41}
          - {id: 904, decidim_question_id: 41}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
        - {id: 41, question_type: 'single_option'}
        - {id: 41, question_type: 'single_option'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 901, decidim_answer_option_id: 1, body: "Nord"}
          - {decidim_answer_id: 904, decidim_answer_option_id: 2, body: "Nord"}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 1, decidim_question_id: 41, body: "Nord"}
          - {id: 2, decidim_question_id: 41, body: "Sud"}
    expect:
      format: dict
      rows:
          - {answer: "Nord", option_answer: "Nord", invalid_choice_body: false}
          - {answer: "Nord", option_answer: "Sud", invalid_choice_body: true}

  - name: answers_single_option_question_check
    description: "Check that single option answers come from options belonging to the answered question"
    model: all_answers_option_and_sorting
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 901, decidim_question_id: 41}
          - {id: 904, decidim_question_id: 41}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
        - {id: 41, question_type: 'single_option'}
        - {id: 41, question_type: 'single_option'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 901, decidim_answer_option_id: 1, body: "Nord"}
          - {decidim_answer_id: 904, decidim_answer_option_id: 9, body: "Rouge"}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 1, decidim_question_id: 41, body: "Nord"}
          - {id: 2, decidim_question_id: 41, body: "Sud"}
          - {id: 8, decidim_question_id: 42, body: "Bleu"}
          - {id: 9, decidim_question_id: 42, body: "Rouge"}
    expect:
      format: dict
      rows:
          - {answer: "Nord", invalid_question_id: false}
          - {answer: "Rouge", invalid_question_id: true}

  - name: answers_multiple_option_content_check
    description: "Check that multiple option answers match pre-written options"
    model: all_answers_option_and_sorting
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 902, decidim_question_id: 42}
          - {id: 905, decidim_question_id: 42}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
        - {id: 42, question_type: 'multiple_option'}
        - {id: 42, question_type: 'multiple_option'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 902, decidim_answer_option_id: 8, body: "Bleu"}
          - {decidim_answer_id: 905, decidim_answer_option_id: 9, body: "Bleu"}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 8, decidim_question_id: 42, body: "Bleu"}
          - {id: 9, decidim_question_id: 42, body: "Rouge"}
          - {id: 10, decidim_question_id: 42, body: "Vert"}
    expect:
      format: dict
      rows:
          - {answer: "Bleu", option_answer: "Bleu", invalid_choice_body: false}
          - {answer: "Bleu", option_answer: "Rouge", invalid_choice_body: true}

  - name: answers_multiple_option_question_check
    description: "Check that multiple option answers come from options belonging to the answered question"
    model: all_answers_option_and_sorting
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 902, decidim_question_id: 42}
          - {id: 905, decidim_question_id: 42}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
        - {id: 42, question_type: 'multiple_option'}
        - {id: 42, question_type: 'multiple_option'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 902, decidim_answer_option_id: 8, body: "Bleu"}
          - {decidim_answer_id: 905, decidim_answer_option_id: 16, body: "Hiver"}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 8, decidim_question_id: 42, body: "Bleu"}
          - {id: 9, decidim_question_id: 42, body: "Rouge"}
          - {id: 10, decidim_question_id: 42, body: "Vert"}
          - {id: 16, decidim_question_id: 43, body: "Hiver"}
    expect:
      format: dict
      rows:
          - {answer: "Bleu", invalid_question_id: false}
          - {answer: "Hiver", invalid_question_id: true}

  - name: answers_sorting_option_content_check
    description: "Check that answers to sorting questions match pre-written options"
    model: all_answers_option_and_sorting
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 903, decidim_question_id: 44}
          - {id: 906, decidim_question_id: 44}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
          - {id: 44, question_type: 'sorting'}
          - {id: 44, question_type: 'sorting'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 903, decidim_answer_option_id: 19, body: "Été"}
          - {decidim_answer_id: 906, decidim_answer_option_id: 18, body: "Été"}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 16, decidim_question_id: 44, body: "Hiver"}
          - {id: 17, decidim_question_id: 44, body: "Printemps"}
          - {id: 18, decidim_question_id: 44, body: "Automne"}
          - {id: 19, decidim_question_id: 44, body: "Été"}
    expect:
      format: dict
      rows:
          - {answer: "Été", option_answer: "Été", invalid_choice_body: false}
          - {answer: "Été", option_answer: "Automne", invalid_choice_body: true}

  - name: answers_sorting_option_question_check
    description: "Check that answers to sorting questions come from options belonging to the answered question"
    model: all_answers_option_and_sorting
    given:
      - input: ref('int_forms_answers')
        format: dict
        rows:
          - {id: 903, decidim_question_id: 44}
          - {id: 906, decidim_question_id: 44}
      - input: ref('stg_decidim_forms_questions')
        format: dict
        rows:
          - {id: 44, question_type: 'sorting'}
          - {id: 44, question_type: 'sorting'}
      - input: ref('stg_decidim_forms_answer_choices')
        format: dict
        rows:
          - {decidim_answer_id: 903, decidim_answer_option_id: 19, body: "Été"}
          - {decidim_answer_id: 906, decidim_answer_option_id: 24, body: "Chocolat"}
      - input: ref('stg_decidim_forms_answer_options')
        format: dict
        rows:
          - {id: 16, decidim_question_id: 44, body: "Hiver"}
          - {id: 17, decidim_question_id: 44, body: "Printemps"}
          - {id: 18, decidim_question_id: 44, body: "Automne"}
          - {id: 19, decidim_question_id: 44, body: "Été"}
          - {id: 24, decidim_question_id: 45, body: "Chocolat"}
    expect:
      format: dict
      rows:
          - {answer: "Été", invalid_question_id: false}
          - {answer: "Chocolat", invalid_question_id: true}
