
version: 2


sources:
  - name: decidim
    database: "{{ env_var('DBNAME') }}"
    schema: public
    tables:
      - name: decidim_budgets_projects
      - name: decidim_budgets_budgets
      - name: decidim_budgets_line_items
      - name: decidim_budgets_orders
models:
  - name: stg_decidim_budgets
    schema: "{{ env_var('TARGET_SCHEMA') }}"
    description: "Lists every budget on the platform and their component"
    columns:
      - name: id
        description: "Unique identifier for a budget"
      - name: title
        description: "Title of the budget"
      - name: decidim_component_id
        description: "ID of the component to which the budget is linked to. Multiple budgets can share the same component"
  - name: stg_decidim_budgets_projects
    schema: "{{ env_var('TARGET_SCHEMA') }}"
    description: "Lists every project for every budget on the platform"
    columns:
      - name: id
        description: "Unique identifier for a project"
      - name: title
        description: "Title of the project"
      - name: description
        description: "Description of the project"
      - name: created_at
        description: "Timestamp of the creation of the project"
      - name: decidim_scope_id
        description: "ID of the scope to which the project may be linked to"
      - name: project_amount
        description: "Cost of the project"
      - name: decidim_budgets_budget_id
        description: "ID of the related budget"
      - name: resource_type
        description: "Hardcoded resource type"
  - name: stg_decidim_budgets_orders
    schema: "{{ env_var('TARGET_SCHEMA') }}"
    description: "An order is a vote from a single user to a given budget, and can be linked to one or several budget projects"
    columns:
      - name: id
        description: "Unique identifier for an order"
      - name: decidim_user_id
        description: "ID of the user who has issued the order"
      - name: checked_out_at
        description: "Timestamp of the completion of the order. Blank if the user has not completed the order"
      - name: created_at
        description: "Timestamp of the creation of the order"
      - name: updated_at
        description: "Timestamp of the last modification of the order"
      - name: decidim_budgets_budget_id
        description: "ID of the budget for which the order is issued"
  - name: stg_decidim_budgets_line_items
    schema: "{{ env_var('TARGET_SCHEMA') }}"
    description: "A line item links a given order to a given budget project"
    columns:
      - name: id
        description: "Unique identifier of the line item"
        data_tests:
          - unique
      - name: decidim_order_id
        description: "ID of the issued order"
      - name: decidim_project_id
        description: "ID of the budget project"
    tests:
      - dbt_utils.unique_combination_of_columns:
        #description: "This test is assuming that no voter ('order') can vote more than once on the same project"
          combination_of_columns:
            - decidim_order_id
            - decidim_project_id

unit_tests:
  - name: resource_type_definition
    description: "Checks that the resource type is properly defined"
    model: stg_decidim_budgets_projects
    given:
      - input: source('decidim', 'decidim_budgets_projects')
        format: dict
        rows:
          - {id: 1}
    expect:
      format: dict
      rows:
          - {resource_type: 'Decidim::Budgets::Project'}







