valbonne:
  target: dev
  outputs:
    dev:
      dbname: "{{ env_var('DBNAME_DEV') }}"
      host: "{{ env_var('HOST') }}"
      pass: "{{ env_var('PASSWORD') }}"
      port: "{{ env_var('PORT') | as_number }}"
      schema: "{{ env_var('TARGET_SCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('USER') }}"
    prod:
      dbname: "{{ env_var('DBNAME_PROD') }}"
      host: "{{ env_var('HOST') }}"
      pass: "{{ env_var('PASSWORD') }}"
      port: "{{ env_var('PORT') | as_number }}"
      schema: "{{ env_var('TARGET_SCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('USER') }}"

