version: 2
 
sources:
  - name: matomo
    database: "{{ env_var('DBNAME') }}"
    schema: matomo
    tables:
      - name: pages
      - name: visits
      - name: referrers
      - name: device_type
      - name: page_titles
      - name : users_city
      - name : downloads