
version: 2

models:
  - name: organizations
    config:
      contract: {enforced: true}
    columns:
      - name: id
        data_type: BIGINT
        constraints:
          - type: unique
          - type: not_null
          - type: primary_key
      - name: name
        data_type: TEXT
      - name: host
        data_type: TEXT
      - name: default_locale
        data_type: TEXT
      - name: available_locales
        data_type: TEXT
      - name: created_at
        data_type: TIMESTAMP
      - name: description
        data_type: TEXT
      - name: secondary_hosts
        data_type: TEXT
      - name: available_authorizations
        data_type: TEXT
      - name: header_snippets
        data_type: TEXT
      - name: tos_version
        data_type: TIMESTAMP
      - name: badges_enabled
        data_type: BOOLEAN
      - name: send_welcome_notification
        data_type: BOOLEAN
      - name: users_registration_mode
        data_type: BIGINT
      - name: time_zone
        data_type: TEXT
  - name: matomo_pages
    schema: "{{ env_var('TARGET_SCHEMA') }}"
    description: "Info related to a page and its associated settings: visits, time spent, exits, date, url, tag"

unit_tests:
  - name: label-parsing
    description: "Checks that relevant info is properly extracted from the URL"
    model: matomo_pages
    given:
      - input: ref('stg_matomo_pages')
        format: dict
        rows:
          - {label: '/processes/budget-participatif-2022/f/2/budgets/1/projects/41'}
          - {label: '/processes/budget-participatif-2022/'}
          - {label: '/assemblies/convention-citoyenne/foo/bar/f/1'}
          - {label: '/budget-participatif-2022/'}
    expect:
      format: dict
      rows:
        - {slug: 'budget-participatif-2022', component_id: 2}
        - {slug: 'budget-participatif-2022', component_id: NULL}
        - {slug: 'convention-citoyenne', component_id: NULL}
        - {slug: '', component_id: NULL}