version: 2

unit_tests:
  - name: testing_that_document_names_are_correctly_extracted
    description: "Checks that document names are correctly extracted from URLs"
    model: int_matomo_downloads
    given:
      - input: ref('stg_matomo_downloads')
        format: dict
        rows:
          - {url: "https://oye.participer.lyon.fr/uploads/decidim/attachment/file/18/Règlement_du_budget_participatif.pdf"}
    expect:
      format: dict
      rows:
        - {document_name: 'Règlement_du_budget_participatif', document_extension: 'pdf'}