version: 2

models:
  - name: forms
    config:
      contract: {enforced: true}
    columns:
      - name: id
        data_type: bigint
        constraints:
          - type: unique
          - type: not_null
          - type: primary_key
      - name: title
        data_type: text
      - name: decidim_component_id
        data_type: bigint
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('components')
            to_columns: [id]
      - name: questionnaire_url
        data_type: text
  - name: forms_answers
    config:
      contract: {enforced: true}
    columns:
      - name: decidim_user_id
        data_type: bigint
        constraints:
          - type: foreign_key
            to: ref('int_users')
            to_columns: [id]
      - name: session_token
        data_type: text
      - name: ip_hash
        data_type: text
      - name: question_type
        data_type: text
      - name: question_title
        data_type: text
      - name: answer
        data_type: text
      - name: sub_matrix_question
        data_type: text
      - name: custom_body
        data_type: text
      - name: sorting_position
        data_type: bigint
      - name: decidim_questionnaire_id
        data_type: bigint
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('forms')
            to_columns: [id]
      - name: form_title
        data_type: text
      - name: decidim_component_id
        data_type: bigint
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('components')
            to_columns: [id]
      - name: sorting_points
        data_type: integer
        description: "In order to evaluate the weight of the sorting answers, points are given to the answer according to its sorting position."
      - name: position
        data_type: bigint
      - name: created_at
        data_type: timestamp
      - name: author_status
        data_type: text
