WITH source AS (
      SELECT * FROM {{ source('decidim', 'decidim_users') }}
),
renamed AS (
    SELECT 
        id,
        email,
        sign_in_count,
        current_sign_in_at,
        last_sign_in_at,
        created_at,
        updated_at,
        invitation_created_at,
        invitation_sent_at,
        invitation_accepted_at,
        invited_by_id,
        invited_by_type,
        decidim_organization_id,
        confirmed_at,
        confirmation_token,
        unconfirmed_email,
        name,
        locale,
        deleted_at,
        admin,
        managed,
        roles::text AS roles,
        nickname,
        accepted_tos_version,
        type,
        following_count,
        followers_count,
        failed_attempts,
        locked_at,
        admin_terms_accepted_at,
        blocked,
        blocked_at,
        (extended_data::jsonb->'spam_detection'->>'spam_probability')::float as spam_probability,
	    extended_data::jsonb->'spam_detection'->> 'reported_at' as spam_report_timestamp,
        NULLIF(extended_data::jsonb->>'date_of_birth', '') AS date_of_birth,
        NULLIF(extended_data::jsonb->>'gender', '') AS gender,
        NULLIF(extended_data::jsonb->>'postal_code', '') AS postal_code,
        NULLIF(extended_data::jsonb->>'half_signup', '') AS half_signup,
        NULLIF(extended_data::jsonb->'half_signup'->>'phone_number', '') AS phone_number,
        NULLIF(extended_data::jsonb->'half_signup'->>'phone_country', '') AS phone_country,
        extended_data
    FROM source
)
SELECT * FROM renamed
