unit_tests:

   - name: testing_that_extended_age_data_matches_age_categories
     description: "Checks that age matching fetches the correct infos "
     model: int_users
     given:
      - input: ref('stg_decidim_users')
        format: dict
        rows:
          - {id: 1, extended_data: '{"date_of_birth": "1955-11-06"}', type: 'Decidim::User'}
          - {id: 2, extended_data: '{"date_of_birth": "1970-06-23"}', type: 'Decidim::User'} 
          - {id: 3, extended_data: '{"date_of_birth": "1932-05-23"}', type: 'Decidim::User'} 
          - {id: 4, extended_data: '{"date_of_birth": "2009-12-01"}', type: 'Decidim::User'}
          - {id: 5, extended_data: null, type: 'Decidim::User'} 
     expect:
      format: dict
      rows:
        - {id: 1, date_of_birth: "1955-11-06", age: 68, age_category: "[65-69 ans]"}
        - {id: 2, date_of_birth: "1970-06-23", age: 54, age_category: "[50-54 ans]"}
        - {id: 3, date_of_birth: "1932-05-23", age: 92, age_category: "[75 ans ou plus]"}
        - {id: 4, date_of_birth: "2009-12-01", age: 14, age_category: "[0-15 ans]"}
        - {id: 5, date_of_birth: null, age: null, age_category: 'Âge non défini'}