unit_tests:
  - name: date_match_test
    description: "Check that proposals with creation dates outside impersonation ranges are properly flagged as not impersonated"
    model: proposals_with_impersonation_info
    given:
      - input: ref('proposals')
        format: dict
        rows:
          - {id: 1, first_author_id: 42, created_at: "2021-08-31 14:12:33.144731"}
          - {id: 1, first_author_id: 43, created_at: "2021-08-31 14:12:34.144731"}
          - {id: 1, first_author_id: 44, created_at: "2021-08-31 14:12:31.144731"}
      - input: ref('decidim_impersonation_logs')
        format: dict
        rows:
          - {user_id: 42, started_at: "2021-08-31 14:12:32", ended_at: "2021-08-31 14:12:34"}
          - {user_id: 43, started_at: "2021-08-31 14:12:32", ended_at: "2021-08-31 14:12:34"}
          - {user_id: 44, started_at: "2021-08-31 14:12:32", ended_at: "2021-08-31 14:12:34"}
    expect:
      format: dict
      rows:
        - {authored_under_impersonation: true}
        - {authored_under_impersonation: false}
        - {authored_under_impersonation: false}            