SELECT 
    decidim_users.id,
    decidim_users.email,
    decidim_users.sign_in_count,
    decidim_users.sign_in_frequency,
    decidim_users.current_sign_in_at,
    decidim_users.last_sign_in_at,
    decidim_users.created_at,
    decidim_users.updated_at,
    decidim_users.invitation_created_at,
    decidim_users.invitation_sent_at,
    decidim_users.invitation_accepted_at,
    decidim_users.invited_by_id,
    decidim_users.invited_by_type,
    decidim_users.decidim_organization_id,
    decidim_users.confirmed_at,
    decidim_users.confirmation_token,
    decidim_users.unconfirmed_email,
    decidim_users.name,
    decidim_users.locale,
    decidim_users.deleted_at,
    decidim_users.admin,
    decidim_users.managed,
    decidim_users.roles,
    decidim_users.nickname,
    decidim_users.accepted_tos_version,
    decidim_users.type,
    decidim_users.following_count,
    decidim_users.followers_count,
    decidim_users.failed_attempts,
    decidim_users.locked_at,
    decidim_users.admin_terms_accepted_at,
    decidim_users.blocked,
    decidim_users.blocked_at,
    decidim_users.confirmed,
    decidim_users.extended_data,
    decidim_users.date_of_birth,
    decidim_users.age_category,
    decidim_users.gender,
    decidim_users.postal_code,
    decidim_users.half_signup
    FROM {{ ref('all_users') }} AS decidim_users
WHERE deleted_at IS NULL
AND decidim_users.blocked != true
AND decidim_users.admin != true
AND decidim_users.confirmed = true